favicon: /img/favicon.ico
banner: 

logo:
  expanded: /img/logo.png
  collapsed: 
  dark: 

flag:
  icon: flag-cn
  name: China

search: true

githubCorner: 

menu:
  - name: 常用工具
    icon: fas fa-tools  # far fa-star
    config: 常用工具  
  - name: 科研专区
    icon: fas fa-lightbulb  # far fa-star
    config: 科研专区
  - name: 校园专区
    icon: iconfont icon-book # iconfont icon-study
    config: 校园专区
  - name: 前端学习
    icon: iconfont icon-cherry # iconfont icon-code
    config: 前端学习
  - name: 人工智能
    icon: fas fa-user    # iconfont icon-cherry
    config: 人工智能
  - name: 童年回忆
    icon: far fa-star
    submenu:
      - name: 小霸王游戏
        icon: far fa-thumbs-up
        config: 小霸王游戏
      - name: 4399小游戏
        icon: far fa-thumbs-up
        config: 4399小游戏
      - name: 动画片
        icon: iconfont icon-video # iconfont icon-photo
        config: 动画片
      - name: 动漫
        icon: iconfont icon-video # iconfont icon-about
        config: 动漫        
      - name: 电视剧
        icon: iconfont icon-video # iconfont icon-about
        config: 电视剧
      - name: 电影
        icon: iconfont icon-video # iconfont icon-about
        config: 电影        



about:
  url: 
  icon: 
  name: 有时简简单单就好了

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是由<a href="https://github.com/hassanblog">Hassan Wong</a>基于<a href="https://hexo.io/">Hexo框架</a>主题为<a href="https://github.com/HCLonely/hexo-theme-webstack">WebStack</a>所搭建的。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Hassan Wong
    url: https://hassanwong.top
    img: 
    description: 时不我待，只争朝夕
    html: ""

since: 2021

busuanzi:
  enable: false
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_2204525_jxth1d6fs6o.css">
    <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" />
  body: # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <div class="bg"></div>
    <script src="/js/custom.js"></script>
    <script src="/js/lozad.min.js"></script>
js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
